[package]
name = "greenwasm-validation"
version = "0.1.0"
authors = ["Marvin LÃ¶bel <loebel.marvin@gmail.com>"]
license = "MIT/Apache-2.0"

readme = "README.md"

workspace = ".."

[dependencies]
greenwasm-structure = { path = "../greenwasm-structure" }
